services:
  mongo:
    image: mongo:7
    container_name: aeroops-mongo
    ports:
      - "27017:27017"
    volumes:
      - aeroops_mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    container_name: aeroops-api
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DATABASE: aeroops
      APP_NAME: AeroOps NoSQL Control Tower
    depends_on:
      - mongo

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: aeroops-dashboard
    ports:
      - "8501:8501"
    environment:
      AEROOPS_API_BASE_URL: http://api:8000
    depends_on:
      - api

volumes:
  aeroops_mongo_data:
