apiVersion: v1
kind: Service
metadata:
  name: aeroops-api-service
  namespace: aeroops
spec:
  selector:
    app: aeroops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP